// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45iORcyaB00Gc-bq-Udv-3ZBw6U2sPYw',
    appId: '1:121550341573:web:d7c657c36c4dc672c077ac',
    messagingSenderId: '121550341573',
    projectId: 'laptop-harbor-3c6cd',
    authDomain: 'laptop-harbor-3c6cd.firebaseapp.com',
    storageBucket: 'laptop-harbor-3c6cd.firebasestorage.app',
    measurementId: 'G-LQQ6ZF05SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZetzY3BviYnRJMgyPwTfg-t9AxHwg5Q',
    appId: '1:121550341573:android:8baaf748213e959ec077ac',
    messagingSenderId: '121550341573',
    projectId: 'laptop-harbor-3c6cd',
    storageBucket: 'laptop-harbor-3c6cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTvICverV94duJHSWqRy7_H-OgVOwpvU',
    appId: '1:121550341573:ios:901d07bfe4020c90c077ac',
    messagingSenderId: '121550341573',
    projectId: 'laptop-harbor-3c6cd',
    storageBucket: 'laptop-harbor-3c6cd.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaTvICverV94duJHSWqRy7_H-OgVOwpvU',
    appId: '1:121550341573:ios:901d07bfe4020c90c077ac',
    messagingSenderId: '121550341573',
    projectId: 'laptop-harbor-3c6cd',
    storageBucket: 'laptop-harbor-3c6cd.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA45iORcyaB00Gc-bq-Udv-3ZBw6U2sPYw',
    appId: '1:121550341573:web:4e13acc439240b6bc077ac',
    messagingSenderId: '121550341573',
    projectId: 'laptop-harbor-3c6cd',
    authDomain: 'laptop-harbor-3c6cd.firebaseapp.com',
    storageBucket: 'laptop-harbor-3c6cd.firebasestorage.app',
    measurementId: 'G-K1SDGTZMC7',
  );
}
